version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  # Staging configuration: run rails in production, but still build the web service Dockerfile and still mount the checked out source code.
  # TODO: a proper production setup would specify an image instead
  web:
    environment:
      - RAILS_ENV=production
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/common_cause
    ports:
      - "80:80"
    depends_on:
      - db
