default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5


development:
  <<: *default
  database: common_cause_development
  username: common_cause
  password: password


test:
  <<: *default
  database: common_cause_test
  username: common_cause
  password: password

production:
  <<: *default
  database: common_cause_production
  username: common_cause
  password: <%= Rails.application.credentials[:production_database_password] %>

